import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function readProjectFile(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

test("AI study card tool is exposed as an independent tool route", async () => {
  const page = await readProjectFile("src/app/tools/study-cards/page.tsx");
  const client = await readProjectFile("src/app/tools/study-cards/StudyCardsTool.tsx");
  const content = await readProjectFile("src/lib/data/thinkingLabContent.ts");
  const sitemap = await readProjectFile("src/app/sitemap.ts");
  const navigation = await readProjectFile("src/components/layout/SiteNavigation.tsx");
  const clientShell = await readProjectFile("src/components/ClientShell.tsx");

  assert.match(page, /AI 学习卡片生成器/);
  assert.match(page, /StudyCardsTool/);
  assert.match(page, /逐张翻看的 AI 问答闪卡/);
  assert.doesNotMatch(page, /概念解释、例子和测试题/);
  assert.match(client, /\/api\/tools\/study-cards/);
  assert.match(client, /问答卡片/);
  assert.match(client, /study-cards-progress/);
  assert.match(client, /progressValue/);
  assert.match(client, /基础：/);
  assert.match(client, /进阶：/);
  assert.match(client, /高级：/);
  assert.doesNotMatch(client, /考试：/);
  assert.doesNotMatch(client, /独立工具/);
  assert.match(content, /slug:\s*"study-cards"/);
  assert.match(content, /href:\s*"\/tools\/study-cards"/);
  assert.match(content, /逐张翻看的 AI 问答闪卡/);
  assert.doesNotMatch(content, /概念解释、例子和测试题/);
  assert.match(sitemap, /\$\{BASE_URL\}\/tools\/study-cards/);
  assert.match(navigation, /\/tools\/study-cards/);
  assert.match(clientShell, /\/tools\/study-cards/);
});

test("AI study card results use an interactive one-card practice flow", async () => {
  const client = await readProjectFile("src/app/tools/study-cards/StudyCardsTool.tsx");
  const styles = await readProjectFile("src/app/globals.css");

  assert.match(client, /activeCardIndex/);
  assert.match(client, /answerRevealed/);
  assert.match(client, /PracticeMode/);
  assert.match(client, /"learn" \| "check"/);
  assert.match(client, /practiceMode/);
  assert.match(client, /hasCompletedLearningRound/);
  assert.match(client, /buildLearningQueue/);
  assert.match(client, /transitionToCheckRound/);
  assert.match(client, /第一轮学习/);
  assert.match(client, /翻看检查/);
  assert.match(client, /全部标记记住了后/);
  assert.match(client, /SAMPLE_RESULT/);
  assert.match(client, /loadSampleContent/);
  assert.match(client, /Harness/);
  assert.match(client, /场景契约/);
  assert.match(client, /setDifficulty\(DIFFICULTY_OPTIONS\[2\]\)/);
  assert.match(client, /轻点这里翻开答案/);
  assert.match(client, /cardMotion/);
  assert.match(client, /dragOffset/);
  assert.match(client, /handleCardPointerDown/);
  assert.match(client, /handleCardPointerMove/);
  assert.match(client, /handleCardPointerUp/);
  assert.match(client, /outputPanelRef/);
  assert.match(client, /focusCardsOnMobile/);
  assert.match(client, /scrollIntoView/);
  assert.match(client, /getNextCardIndex/);
  assert.match(client, /getPreviousCardIndex/);
  assert.match(client, /memoryStats/);
  assert.match(client, /reviewQueue/);
  assert.match(client, /rateActiveCard/);
  assert.match(client, /scheduleRatedCard/);
  assert.match(client, /记住了/);
  assert.match(client, /不熟练/);
  assert.match(client, /左滑下一张/);
  assert.match(client, /右滑上一张/);
  assert.match(client, /study-cards-deck/);
  assert.match(client, /study-cards-deck-shell/);
  assert.match(client, /study-cards-card-stage/);
  assert.match(client, /study-cards-nav-arrow/);
  assert.match(client, /study-cards-question-block/);
  assert.match(client, /study-cards-recall-hint/);
  assert.match(client, /study-cards-memory-actions/);
  assert.match(client, /study-cards-answer-panel/);
  assert.match(client, /study-cards-practice-card/);
  assert.doesNotMatch(client, /study-cards-practice-actions/);
  assert.match(styles, /\.study-cards-deck::before/);
  assert.match(styles, /\.study-cards-deck::after/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*inset: 0/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*linear-gradient\(90deg,\s*var\(--accent\)/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*calc\(100% - 44px\)\s*calc\(100% - 212px\)/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*translateX\(-34%\)/);
  assert.match(styles, /\.study-cards-deck::after[\s\S]*translateX\(34%\)/);
  assert.match(styles, /\.study-cards-deck-shell/);
  assert.match(styles, /\.study-cards-card-stage/);
  assert.match(styles, /\.study-cards-nav-arrow/);
  assert.match(styles, /\.study-cards-memory-actions/);
  assert.match(styles, /--drag-x/);
  assert.match(styles, /aspect-ratio:\s*3\s*\/\s*4/);
  assert.match(styles, /min-height:\s*min\(470px,\s*calc\(100dvh - 250px\)\)/);
  assert.match(styles, /cursor: grab/);
  assert.match(styles, /\.study-cards-question-block/);
  assert.match(styles, /\.study-cards-recall-hint/);
  assert.match(styles, /@media \(max-width: 560px\)[\s\S]*\.study-cards-deck::before[\s\S]*display: none/);
  assert.match(styles, /@media \(max-width: 760px\) and \(orientation: portrait\)/);
  assert.match(styles, /min-height:\s*calc\(100dvh - 22px\)/);
  assert.match(styles, /@keyframes study-cards-card-exit-next/);
  assert.match(styles, /@keyframes study-cards-answer-reveal/);
  assert.match(styles, /\.study-cards-practice-card/);
  assert.match(styles, /\.study-cards-card-progress/);

  assert.doesNotMatch(client, /复制 Anki TSV/);
  assert.doesNotMatch(client, /cardToTsv/);
  assert.doesNotMatch(client, /ankiTsv/);
  assert.doesNotMatch(client, /Clipboard/);
  assert.doesNotMatch(client, /CheckCircle2/);
  assert.doesNotMatch(client, /is-answer/);
  assert.doesNotMatch(client, /study-cards-card-grid/);
  assert.doesNotMatch(client, /study-cards-flash-card/);
  assert.doesNotMatch(client, /study-cards-concept/);
  assert.doesNotMatch(client, /study-cards-quiz/);
  assert.doesNotMatch(client, /ListChecks/);
  assert.doesNotMatch(client, /StudyQuiz/);
});

test("AI study card endpoint asks for structured learning output", async () => {
  const route = await readProjectFile("src/app/api/tools/study-cards/route.ts");

  assert.match(route, /cards/);
  assert.match(route, /JSON/);
  assert.match(route, /CHAT_API_KEY/);
  assert.match(route, /DEEPSEEK_API_KEY/);
  assert.match(route, /response_format/);
  assert.match(route, /60000/);
  assert.match(route, /errorCode/);
  assert.match(route, /API_NOT_CONFIGURED/);
  assert.match(route, /每张卡只考一个知识点/);
  assert.match(route, /front 必须是简短问题/);
  assert.match(route, /back 不超过 70 个中文字符/);
  assert.match(route, /note 是给学习者的提示/);
  assert.match(route, /答案显示前/);
  assert.doesNotMatch(route, /测试题生成/);
  assert.doesNotMatch(route, /StudyQuiz/);
  assert.match(route, /export async function POST/);
});
