import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

async function readProjectFile(path) {
  return readFile(new URL(`../${path}`, import.meta.url), "utf8");
}

test("AI study card tool is exposed as an independent tool route", async () => {
  const page = await readProjectFile("src/app/tools/study-cards/page.tsx");
  const client = await readProjectFile("src/app/tools/study-cards/StudyCardsTool.tsx");
  const content = await readProjectFile("src/lib/data/thinkingLabContent.ts");
  const sitemap = await readProjectFile("src/app/sitemap.ts");
  const navigation = await readProjectFile("src/components/layout/SiteNavigation.tsx");
  const clientShell = await readProjectFile("src/components/ClientShell.tsx");

  assert.match(page, /AI 学习卡片生成器/);
  assert.match(page, /StudyCardsTool/);
  assert.match(page, /逐张翻看的 AI 问答闪卡/);
  assert.doesNotMatch(page, /概念解释、例子和测试题/);
  assert.match(client, /\/api\/tools\/study-cards/);
  assert.match(client, /问答卡片/);
  assert.match(client, /study-cards-progress/);
  assert.match(client, /progressValue/);
  assert.match(client, /基础：/);
  assert.match(client, /进阶：/);
  assert.match(client, /高级：/);
  assert.doesNotMatch(client, /考试：/);
  assert.doesNotMatch(client, /独立工具/);
  assert.match(content, /slug:\s*"study-cards"/);
  assert.match(content, /href:\s*"\/tools\/study-cards"/);
  assert.match(content, /逐张翻看的 AI 问答闪卡/);
  assert.doesNotMatch(content, /概念解释、例子和测试题/);
  assert.match(sitemap, /\$\{BASE_URL\}\/tools\/study-cards/);
  assert.match(navigation, /\/tools\/study-cards/);
  assert.match(clientShell, /\/tools\/study-cards/);
  assert.doesNotMatch(clientShell.match(/function shouldHideAssistant[\s\S]*?\n}/)?.[0] ?? "", /study-cards/);
});

test("AI study card results use an interactive one-card practice flow", async () => {
  const client = await readProjectFile("src/app/tools/study-cards/StudyCardsTool.tsx");
  const styles = await readProjectFile("src/app/globals.css");

  assert.match(client, /activeCardIndex/);
  assert.match(client, /answerRevealed/);
  assert.match(client, /has-result/);
  assert.match(client, /PracticeMode/);
  assert.match(client, /"learn" \| "check"/);
  assert.match(client, /practiceMode/);
  assert.match(client, /hasCompletedLearningRound/);
  assert.match(client, /buildLearningQueue/);
  assert.match(client, /transitionToCheckRound/);
  assert.match(client, /第一轮学习/);
  assert.match(client, /翻看检查/);
  assert.match(client, /已通过/);
  assert.match(client, /不熟练会近期复现/);
  assert.match(client, /SAMPLE_RESULT/);
  assert.match(client, /loadSampleContent/);
  assert.match(client, /青少年心理健康危机日益凸显/);
  assert.match(client, /彭凯平/);
  assert.match(client, /生命教育与青少年危机/);
  assert.match(client, /生命教育为何走向焦点/);
  assert.match(client, /彭凯平团队发现哪“四无”/);
  assert.match(client, /生命教育最终使命是什么/);
  assert.match(client, /setDifficulty\(DIFFICULTY_OPTIONS\[2\]\)/);
  assert.match(client, /study-cards-empty-preview/);
  assert.match(client, /试试看这种卡片/);
  assert.match(client, /先判断，再翻面/);
  assert.match(client, /轻点这里翻开答案/);
  assert.match(client, /cardMotion/);
  assert.match(client, /dragOffset/);
  assert.match(client, /handleCardPointerDown/);
  assert.match(client, /handleCardPointerMove/);
  assert.match(client, /handleCardPointerUp/);
  assert.match(client, /outputPanelRef/);
  assert.match(client, /focusCardsOnMobile/);
  assert.match(client, /mobilePracticeActive/);
  assert.match(client, /is-mobile-practice/);
  assert.match(client, /returnToInputOnMobile/);
  assert.match(client, /编辑内容/);
  assert.match(client, /scrollIntoView/);
  assert.match(client, /getNextCardIndex/);
  assert.match(client, /getPreviousCardIndex/);
  assert.match(client, /advanceActiveCard/);
  assert.match(client, /左滑或点右箭头表示通过/);
  assert.match(client, /type CardTextDensity = "normal" \| "dense" \| "compact"/);
  assert.match(client, /getCardTextDensity/);
  assert.match(client, /activeCardDensity/);
  assert.match(client, /is-density-\$\{activeCardDensity\}/);
  assert.match(client, /memoryStats/);
  assert.match(client, /reviewQueue/);
  assert.match(client, /rateActiveCard/);
  assert.match(client, /不熟练/);
  assert.match(client, /答对就继续下一张/);
  assert.match(client, /右滑回看上一张/);
  assert.match(client, /study-cards-deck/);
  assert.match(client, /study-cards-deck-shell/);
  assert.match(client, /study-cards-card-stage/);
  assert.match(client, /study-cards-nav-arrow/);
  assert.match(client, /study-cards-question-block/);
  assert.match(client, /study-cards-recall-hint/);
  assert.match(client, /study-cards-memory-actions/);
  assert.match(client, /study-cards-answer-panel/);
  assert.match(client, /study-cards-practice-card/);
  assert.match(client, /compactText\(activeCard\.front,\s*72\)/);
  assert.match(client, /compactText\(activeCard\.note,\s*96\)/);
  assert.match(client, /compactText\(activeCard\.back,\s*240\)/);
  assert.match(client, /正在打磨卡片答案/);
  assert.doesNotMatch(client, /study-cards-practice-actions/);
  assert.match(styles, /\.study-cards-deck::before/);
  assert.match(styles, /\.study-cards-deck::after/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*inset: 0/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*linear-gradient\(90deg,\s*var\(--accent\)/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*calc\(100% - 44px\)\s*calc\(100% - 212px\)/);
  assert.match(styles, /\.study-cards-deck::before[\s\S]*translateX\(-34%\)/);
  assert.match(styles, /\.study-cards-deck::after[\s\S]*translateX\(34%\)/);
  assert.match(styles, /\.study-cards-deck-shell/);
  assert.match(styles, /\.study-cards-card-stage/);
  assert.match(styles, /\.study-cards-nav-arrow/);
  assert.match(styles, /\.study-cards-memory-actions/);
  assert.match(styles, /\.study-cards-page\.has-result \.study-cards-workspace/);
  assert.match(styles, /\.study-cards-page\.has-result \.study-cards-textarea/);
  assert.match(styles, /\.study-cards-empty-preview/);
  assert.match(styles, /\.study-cards-empty-card/);
  assert.match(styles, /\.study-cards-empty-answer/);
  assert.match(styles, /grid-template-columns:\s*auto minmax\(0,\s*1fr\)/);
  assert.match(styles, /--drag-x/);
  assert.match(styles, /aspect-ratio:\s*3\s*\/\s*4/);
  assert.match(styles, /min-height:\s*min\(470px,\s*calc\(100dvh - 250px\)\)/);
  assert.match(styles, /cursor: grab/);
  assert.match(styles, /\.study-cards-question-block/);
  assert.match(styles, /\.study-cards-recall-hint/);
  assert.match(styles, /\.study-cards-answer-panel\.is-hidden/);
  assert.match(styles, /--study-card-question-size/);
  assert.match(styles, /--study-card-answer-size/);
  assert.match(styles, /\.study-cards-practice-card\.is-density-dense/);
  assert.match(styles, /\.study-cards-practice-card\.is-density-compact/);
  assert.match(styles, /\.study-cards-answer-panel\.is-revealed[\s\S]*overflow-y:\s*auto/);
  assert.match(styles, /-webkit-line-clamp:\s*var\(--study-card-question-lines\)/);
  assert.match(styles, /\.study-cards-mobile-edit-button/);
  assert.match(styles, /@media \(max-width: 560px\)[\s\S]*\.study-cards-empty/);
  assert.match(styles, /@media \(max-width: 560px\)[\s\S]*\.study-cards-deck::before[\s\S]*display: none/);
  assert.match(styles, /@media \(max-width: 760px\) and \(orientation: portrait\)/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice[\s\S]*position: fixed/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice[\s\S]*overflow: hidden/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice \.study-cards-input-panel[\s\S]*display: none/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice \.study-cards-deck-shell[\s\S]*align-items: flex-start/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice \.study-cards-deck[\s\S]*width: min\(100%, 360px\)/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice \.study-cards-deck::before[\s\S]*display: block/);
  assert.match(styles, /\.study-cards-page\.is-mobile-practice \.study-cards-card-stage[\s\S]*touch-action: none/);
  assert.match(styles, /min-height:\s*calc\(100dvh - 22px\)/);
  assert.match(styles, /@keyframes study-cards-card-exit-next/);
  assert.match(styles, /@keyframes study-cards-answer-reveal/);
  assert.match(styles, /\.study-cards-practice-card/);
  assert.match(styles, /\.study-cards-card-progress/);

  assert.doesNotMatch(client, /复制 Anki TSV/);
  assert.doesNotMatch(client, /cardToTsv/);
  assert.doesNotMatch(client, /ankiTsv/);
  assert.doesNotMatch(client, /Clipboard/);
  assert.doesNotMatch(client, /CheckCircle2/);
  assert.doesNotMatch(client, /记住了/);
  assert.doesNotMatch(client, /is-remembered/);
  assert.doesNotMatch(client, /何时需要 Harness 介入/);
  assert.doesNotMatch(client, /夹具与真实调用怎么分工/);
  assert.doesNotMatch(client, /为何不能只看格式断言/);
  assert.doesNotMatch(client, /评判器分层解决什么/);
  assert.doesNotMatch(client, /Harness 服务哪种目标/);
  assert.doesNotMatch(client, /Harness 的核心边界是什么/);
  assert.doesNotMatch(client, /重点不是脚本/);
  assert.doesNotMatch(client, /is-answer/);
  assert.doesNotMatch(client, /study-cards-card-grid/);
  assert.doesNotMatch(client, /study-cards-flash-card/);
  assert.doesNotMatch(client, /study-cards-concept/);
  assert.doesNotMatch(client, /study-cards-quiz/);
  assert.doesNotMatch(client, /ListChecks/);
  assert.doesNotMatch(client, /StudyQuiz/);
  assert.doesNotMatch(client, /AI Harness 质量评测/);
  assert.doesNotMatch(client, /切模型后怎么判断质量变化来源/);
  assert.doesNotMatch(client, /场景契约/);
  assert.doesNotMatch(client, /工具超时/);

  const sampleCards = Array.from(
    client.matchAll(/front: "([^"]+)",\s+back: "([^"]+)",\s+note: "([^"]+)"/g),
    ([, front, back, note]) => ({ front, back, note }),
  );
  assert.equal(sampleCards.length, 6);
  for (const card of sampleCards) {
    assert.ok(card.front.length <= 56, `sample front is too long: ${card.front}`);
    assert.ok(card.back.length <= 220, `sample back is too long: ${card.back}`);
    assert.ok(card.note.length <= 48, `sample note is too long: ${card.note}`);
    assert.doesNotMatch(card.front, /^什么是/);
    assert.doesNotMatch(card.front, /^什么叫/);
  }
});

test("AI study card endpoint asks for structured learning output", async () => {
  const route = await readProjectFile("src/app/api/tools/study-cards/route.ts");

  assert.match(route, /cards/);
  assert.match(route, /JSON/);
  assert.match(route, /CHAT_API_KEY/);
  assert.match(route, /DEEPSEEK_API_KEY/);
  assert.match(route, /response_format/);
  assert.match(route, /60000/);
  assert.match(route, /errorCode/);
  assert.match(route, /API_NOT_CONFIGURED/);
  assert.match(route, /每张卡只考一个知识点/);
  assert.match(route, /信息密度优先/);
  assert.match(route, /深度递进/);
  assert.match(route, /优先挖掘材料里的因果链、矛盾张力、隐含前提、关键转折和作者判断依据/);
  assert.match(route, /不要停留在表层事实清单/);
  assert.match(route, /忠于原文/);
  assert.match(route, /不得引入原文没有出现的人名、数据、概念、案例、结论或外部背景/);
  assert.match(route, /每个 back 都必须能在用户内容里找到依据/);
  assert.match(route, /材料没有依据的判断不要生成卡片/);
  assert.match(route, /不要根据常识/);
  assert.match(route, /front 可以是一句具体问题/);
  assert.match(route, /建议 12 到 56 个中文字符/);
  assert.match(route, /必要时可以稍长/);
  assert.match(route, /back 通常写 1 到 3 句/);
  assert.match(route, /建议 100 到 220 个中文字符/);
  assert.match(route, /不要因为字数范围删掉关键限定/);
  assert.match(route, /note 是给学习者的提示/);
  assert.match(route, /通常 12 到 48 个中文字符/);
  assert.match(route, /答案显示前/);
  assert.match(route, /问题必须考判断、关系、边界或因果/);
  assert.match(route, /答案必须能脱离原文独立复述/);
  assert.match(route, /不要把原文句子拆短后照搬/);
  assert.match(route, /提示只能给回忆方向/);
  assert.match(route, /出题框架/);
  assert.match(route, /适用条件/);
  assert.match(route, /区分边界/);
  assert.match(route, /因果机制/);
  assert.match(route, /迁移判断/);
  assert.match(route, /反例纠错/);
  assert.match(route, /同一题型不要连续出现超过 2 张/);
  assert.match(route, /不要问“核心是什么”/);
  assert.match(route, /先判断，再解释依据/);
  assert.match(route, /生成前先自检/);
  assert.match(route, /基础难度/);
  assert.match(route, /基础难度：抓住材料里的关键事实、明确因果和核心关系/);
  assert.match(route, /进阶难度/);
  assert.match(route, /进阶难度：追问材料中的关系、张力、原因、后果和边界/);
  assert.match(route, /高级难度/);
  assert.match(route, /高级难度：优先挖掘深层结构/);
  assert.doesNotMatch(route, /front 必须是简短问题/);
  assert.doesNotMatch(route, /back 不超过 70 个中文字符/);
  assert.doesNotMatch(route, /不超过 24 个中文字符/);
  assert.doesNotMatch(route, /不超过 42 个中文字符/);
  assert.doesNotMatch(route, /不超过 36 个中文字符/);
  assert.doesNotMatch(route, /建议 80 到 150 个中文字符/);
  assert.doesNotMatch(route, /测试题生成/);
  assert.doesNotMatch(route, /StudyQuiz/);
  assert.match(route, /export async function POST/);
});
